// Generated by gencpp from file raspimouse_ros/SwitchMotorsRequest.msg
// DO NOT EDIT!


#ifndef RASPIMOUSE_ROS_MESSAGE_SWITCHMOTORSREQUEST_H
#define RASPIMOUSE_ROS_MESSAGE_SWITCHMOTORSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace raspimouse_ros
{
template <class ContainerAllocator>
struct SwitchMotorsRequest_
{
  typedef SwitchMotorsRequest_<ContainerAllocator> Type;

  SwitchMotorsRequest_()
    : on(false)  {
    }
  SwitchMotorsRequest_(const ContainerAllocator& _alloc)
    : on(false)  {
  (void)_alloc;
    }



   typedef uint8_t _on_type;
  _on_type on;





  typedef boost::shared_ptr< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SwitchMotorsRequest_

typedef ::raspimouse_ros::SwitchMotorsRequest_<std::allocator<void> > SwitchMotorsRequest;

typedef boost::shared_ptr< ::raspimouse_ros::SwitchMotorsRequest > SwitchMotorsRequestPtr;
typedef boost::shared_ptr< ::raspimouse_ros::SwitchMotorsRequest const> SwitchMotorsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace raspimouse_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'raspimouse_ros': ['/home/ubuntu/catkin_ws/src/raspimouse_ros/msg', '/home/ubuntu/catkin_ws/devel/share/raspimouse_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74983d2ffe4877de8ae30b7a94625c41";
  }

  static const char* value(const ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74983d2ffe4877deULL;
  static const uint64_t static_value2 = 0x8ae30b7a94625c41ULL;
};

template<class ContainerAllocator>
struct DataType< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raspimouse_ros/SwitchMotorsRequest";
  }

  static const char* value(const ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool on\n\
";
  }

  static const char* value(const ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.on);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwitchMotorsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator>& v)
  {
    s << indent << "on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.on);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASPIMOUSE_ROS_MESSAGE_SWITCHMOTORSREQUEST_H
