// Generated by gencpp from file raspimouse_ros/SwitchMotorsResponse.msg
// DO NOT EDIT!


#ifndef RASPIMOUSE_ROS_MESSAGE_SWITCHMOTORSRESPONSE_H
#define RASPIMOUSE_ROS_MESSAGE_SWITCHMOTORSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace raspimouse_ros
{
template <class ContainerAllocator>
struct SwitchMotorsResponse_
{
  typedef SwitchMotorsResponse_<ContainerAllocator> Type;

  SwitchMotorsResponse_()
    : accepted(false)  {
    }
  SwitchMotorsResponse_(const ContainerAllocator& _alloc)
    : accepted(false)  {
  (void)_alloc;
    }



   typedef uint8_t _accepted_type;
  _accepted_type accepted;





  typedef boost::shared_ptr< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SwitchMotorsResponse_

typedef ::raspimouse_ros::SwitchMotorsResponse_<std::allocator<void> > SwitchMotorsResponse;

typedef boost::shared_ptr< ::raspimouse_ros::SwitchMotorsResponse > SwitchMotorsResponsePtr;
typedef boost::shared_ptr< ::raspimouse_ros::SwitchMotorsResponse const> SwitchMotorsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace raspimouse_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'raspimouse_ros': ['/home/ubuntu/catkin_ws/src/raspimouse_ros/msg', '/home/ubuntu/catkin_ws/devel/share/raspimouse_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ea39b897cc8620c46aaa14cb60920cd";
  }

  static const char* value(const ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ea39b897cc8620cULL;
  static const uint64_t static_value2 = 0x46aaa14cb60920cdULL;
};

template<class ContainerAllocator>
struct DataType< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raspimouse_ros/SwitchMotorsResponse";
  }

  static const char* value(const ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool accepted\n\
\n\
";
  }

  static const char* value(const ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accepted);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwitchMotorsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator>& v)
  {
    s << indent << "accepted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.accepted);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASPIMOUSE_ROS_MESSAGE_SWITCHMOTORSRESPONSE_H
